project:
  type: website

website:
  title: "Jamil Ramirez"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: publications.qmd
      text: Publications
    - href: research-radar.qmd
      text: Radar
    - href: projects.qmd
      text: Projects
    - href: blog.qmd
      text: Blog
    - href: CV.qmd
      text: CV
    - href: about.qmd
      text: About

format:
  html:
    theme:
      - litera
      - custom.scss
    css: styles.css
    toc: true
editor: visual